version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Server deps update: "
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/gui"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "GUI deps update: "
    labels:
      - "dependencies"
